ALTER TABLE daily_finance_accounts ALTER COLUMN finance_date DROP NOT NULL;
CREATE TABLE IF NOT EXISTS daily_finance_historical_collections (historical_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), customer_id UUID NOT NULL REFERENCES daily_finance_customers(customer_id), finance_id UUID NOT NULL REFERENCES daily_finance_accounts(finance_id), period_label VARCHAR(40) NOT NULL, amount NUMERIC(14,2) NOT NULL CHECK(amount>=0), source VARCHAR(120) NOT NULL DEFAULT 'Sheet1', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_df_historical_finance ON daily_finance_historical_collections(finance_id);
BEGIN;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'selvaraj','Historical Sheet1 import; source date: 22.05.2027'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2027-05-22',50000.0,5500.0,50000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 22.05.2027');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'May',2500.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',5000.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',14200.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',15500.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'periyasamy','Historical Sheet1 import; source date: 22.05.2027'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2027-05-22',100000.0,11000.0,100000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 22.05.2027');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'May',3000.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',5500.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',10200.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',13000.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'iyyankar','Historical Sheet1 import; source date: 22.05.2028'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2028-05-22',100000.0,11000.0,100000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 22.05.2028');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'May',3000.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',4500.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',5400.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',10500.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'manikandan','Historical Sheet1 import; source date: 23.05.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-05-23',50000.0,6000.0,50000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 23.05.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'May',2500.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',6000.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',7300.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',12800.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'ayuphan','Historical Sheet1 import; source date: 27.05.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-05-27',50000.0,5000.0,50000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 27.05.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'May',4500.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',6500.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',3700.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',11900.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'kalanjiyam','Historical Sheet1 import; source date: 27.05.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-05-27',100000.0,10000.0,100000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 27.05.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'May',7500.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',10500.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',12500.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',13400.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'prakash','Historical Sheet1 import; source date: 28.05.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-05-28',50000.0,5000.0,50000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 28.05.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'May',5000.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',6000.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',6200.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',9000.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'raja','Historical Sheet1 import; source date: 28.05.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-05-28',50000.0,5000.0,50000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 28.05.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'May',5000.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',6000.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',9700.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',19500.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'ramya','Historical Sheet1 import; source date: 03.06.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-06-03',150000.0,15000.0,150000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 03.06.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',6000.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',6600.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',11300.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'maheshwari','Historical Sheet1 import; source date: 09.06.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-06-09',40000.0,4000.0,40000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 09.06.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',6000.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',5200.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',17000.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'muniyandi','Historical Sheet1 import; source date: 09.06.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-06-09',20000.0,2000.0,20000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 09.06.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',7900.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',14700.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',9300.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'muthuveeran','Historical Sheet1 import; source date: 09.06.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-06-09',50000.0,5000.0,50000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 09.06.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',10500.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',6000.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',11100.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'jeyalakshmi','Historical Sheet1 import; source date: 24.06.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-06-24',20000.0,2000.0,20000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 24.06.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',5000.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',9500.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',11700.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'selvakumar','Historical Sheet1 import; source date: 24.06.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-06-24',20000.0,2000.0,20000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 24.06.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',8500.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',5500.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',10600.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'a.rajkumar','Historical Sheet1 import; source date: 06.07.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-07-06',20000.0,2000.0,20000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 06.07.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',7400.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',4000.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',14200.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'m.rajkumar','Historical Sheet1 import; source date: 06.07.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-07-06',10000.0,1000.0,10000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 06.07.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',6700.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',10200.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',9400.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'g.sudhasan','Historical Sheet1 import; source date: 13.07.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-07-13',10000.0,1000.0,10000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 13.07.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',8500.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',5400.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',33200.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'palpandi','Historical Sheet1 import; source date: 20.07.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-07-20',10000.0,5000.0,10000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 20.07.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',5400.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',5000.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',9700.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'thangaraj','Historical Sheet1 import; source date: 19.07.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-07-19',50000.0,1000.0,50000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 19.07.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',10000.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',6500.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',11900.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'s.elamparuthi','Historical Sheet1 import; source date: 21.07.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-07-21',30000.0,3000.0,30000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 21.07.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',5400.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',8000.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',15000.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'s.karthic','Historical Sheet1 import; source date: 21.07.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-07-21',15000.0,1500.0,15000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 21.07.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',5000.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',7000.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',9200.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'t.selvam','Historical Sheet1 import; source date: 21.07.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-07-21',50000.0,5000.0,50000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 21.07.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',8900.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',6700.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',10300.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'g.suresh','Historical Sheet1 import; source date: 22.07.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-07-22',20000.0,2000.0,20000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 22.07.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',8700.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',8300.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',9300.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'r.vijayakanth','Historical Sheet1 import; source date: 22.07.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-07-22',30000.0,3000.0,30000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 22.07.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',5000.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',7400.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',13600.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'beerilahi','Historical Sheet1 import; source date: 22.07.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-07-22',50000.0,5000.0,50000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 22.07.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',5600.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',9300.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',16200.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'e.arulpandi','Historical Sheet1 import; source date: 23.07.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-07-23',40000.0,4000.0,40000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 23.07.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',7800.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',9550.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',16600.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'m.bilal','Historical Sheet1 import; source date: 25.07.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-07-25',70000.0,7000.0,70000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 25.07.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',5200.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',10000.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',13100.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'s.abishek','Historical Sheet1 import; source date: 27.07.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-07-27',20000.0,2000.0,20000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 27.07.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',3600.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',6900.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',9700.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'m.s.pandian','Historical Sheet1 import; source date: 27.07.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-07-27',20000.0,2000.0,20000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 27.07.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',4800.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',9800.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',13400.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'m.thivan','Historical Sheet1 import; source date: 28,07.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-07-28',50000.0,5000.0,50000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 28,07.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',5100.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',6900.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',13700.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'k.saravanakarthic','Historical Sheet1 import; source date: 30.07.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-07-30',50000.0,5000.0,50000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 30.07.2026');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',13500.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',22400.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'r.saravanan','Historical Sheet1 import; source date: 31.07.206'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,NULL,20000.0,2000.0,20000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 31.07.206');
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'May',33000.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'June',197000.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'July',251150.0);
INSERT INTO daily_finance_historical_collections(customer_id,finance_id,period_label,amount) VALUES(cid,fid,'August',417500.0);
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'prabakaran','Historical Sheet1 import; source date: 31.07.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-07-31',100000.0,10000.0,100000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 31.07.2026');
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'beerilahi','Historical Sheet1 import; source date: 1.08.206'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,NULL,150000.0,51000.0,150000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 1.08.206');
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'vasanth','Historical Sheet1 import; source date: 2.08.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-08-02',20000.0,2000.0,20000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 2.08.2026');
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'madhan','Historical Sheet1 import; source date: .08.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,NULL,20000.0,2000.0,20000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: .08.2026');
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'suganya','Historical Sheet1 import; source date: 3.08.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-08-03',30000.0,3000.0,30000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 3.08.2026');
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'vijay','Historical Sheet1 import; source date: 12.8.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-08-12',10000.0,1000.0,10000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 12.8.2026');
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'jegadeeswaran','Historical Sheet1 import; source date: 14.8.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-08-14',30000.0,3000.0,30000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 14.8.2026');
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'ramya','Historical Sheet1 import; source date: 14.08.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-08-14',45000.0,4500.0,45000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 14.08.2026');
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'prakash','Historical Sheet1 import; source date: 14.08.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-08-14',50000.0,25000.0,50000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 14.08.2026');
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'selvaraj','Historical Sheet1 import; source date: 18.08.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-08-18',50000.0,5000.0,50000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 18.08.2026');
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'rajkumar','Historical Sheet1 import; source date: 20.08.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-08-20',10000.0,1000.0,10000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 20.08.2026');
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'raja','Historical Sheet1 import; source date: 21.08.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-08-21',60000.0,6000.0,60000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 21.08.2026');
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'kathiresan','Historical Sheet1 import; source date: 24.08.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-08-24',30000.0,3000.0,30000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 24.08.2026');
END $$;
DO $$ DECLARE cid UUID := gen_random_uuid(); fid UUID := gen_random_uuid(); BEGIN INSERT INTO daily_finance_customers(customer_id,customer_name,notes) VALUES(cid,'kumar','Historical Sheet1 import; source date: 30.08.2026'); INSERT INTO daily_finance_accounts(finance_id,customer_id,finance_date,gross_finance_amount,initial_deduction,agreed_total_payable,daily_agreed_due,expected_collection_days,status,notes) VALUES(fid,cid,'2026-08-30',70000.0,19300.0,70000.0,0,0,'ACTIVE','Historical Sheet1 import; source date: 30.08.2026');
END $$;
COMMIT;